name: Checks

on:
  pull_request:
    paths-ignore: [.vscode/**, .github/**, docs/**, dist/**]
    branches: [ master ]

jobs:

  # Checks that the Angular projects conforms to standards
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Installing dependencies
      run: npm ci

    - name: Linting Angular projects
      run: npm run lint

  # Checks that all stylesheets conform to standards
  lint-stylesheets:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Installing dependencies
      run: npm ci

    - name: Linting all stylesheets
      run: npm run lint-style

  # Checks that the Angular app successfully builds using ahead-of-time compilation
  build:
    runs-on: ubuntu-latest
    needs: [lint-app, lint-stylesheets]
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Installing dependencies
      run: npm ci

    - name: Building Angular web project
      run: npm run build

  # Checks that the Angular app passes all defined unit and integration tests
  test:
    # runs-on: ubuntu-latest
    # needs: build
    # timeout-minutes: 5

    # steps:
    # - uses: actions/checkout@v2

    # - name: Installing dependencies
    #   run: npm ci

    # - name: Running all unit and integration tests
    #   run: npm run test-ci
